version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run: node --version
      - run: yarn --version

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: ./misc/rebuild_refs.sh
      - run: yarn ci
